### ISSUE TITLE
Typos in decode error message

### ISSUE THREAD

**Issue by LetUsFlow** [Giftzwerg02/rustcii#1]
When trying to decode a string that is not exciting, blazingly (🦀) fast (🚀) and - most important of all - superior, the shown error message contains a few unacceptable mistakes.
1. The rust crab emoji (🦀) isn't enclosed in quotes ('🦀')
2. The 'O' in "GO-Programmer" should be written in lowercase ("Go-Programmer")

![grafik](https://user-images.githubusercontent.com/32359801/184636782-d5fec900-0999-4744-bf8e-accee70b1c92.png)

**Comment by LetUsFlow** [comment]
When considering the second point, you could also write "Golang-Programmer" to upset the Go-Community as much as possible.

**Comment by Giftzwerg02** [comment]
I am very sorry for this inconvenience, I have already started creating a business plan to reflect on fixing these mentioned issues. I'll respond again once a plan-of-action has been thoroughly developed.

Kind regards.

**Comment by LetUsFlow** [comment]
#2

**Comment by LetUsFlow** [comment]
Fixed by #2
